FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.24 AS builder

ARG SOURCE_DIR="/go/src/github.com/openshift/spiffe-spire"
WORKDIR ${SOURCE_DIR}

COPY spiffe-spire .
COPY spiffe-spire/LICENSE /licenses/.


ENV CGO_ENABLED=1
ENV GOFLAGS=""
ENV GO_BUILD_TAGS=strictfipsruntime,openssl
ENV GOEXPERIMENT=strictfipsruntime

RUN go build -o bin/spire-agent -ldflags '-w -s' -tags ${GO_BUILD_TAGS} cmd/spire-agent/main.go

FROM registry.redhat.io/ubi9/ubi-minimal:latest@sha256:6fc28bcb6776e387d7a35a2056d9d2b985dc4e26031e98a2bd35a7137cd6fd71

ARG RELEASE_VERSION
ARG COMMIT_SHA
ARG SOURCE_URL
ARG SOURCE_DIR="/go/src/github.com/openshift/spiffe-spire"

COPY --from=builder ${SOURCE_DIR}/bin/spire-agent /spire-agent
COPY --from=builder /licenses /licenses

# Run as root user
USER 0:0

LABEL com.redhat.component="spire-agent-container" \
      name="zero-trust-workload-identity-manager/spiffe-spire-agent-rhel9" \
      version="${RELEASE_VERSION}" \
      summary="SPIRE Agent Component" \
      maintainer="Red Hat, Inc." \
      description="SPIRE Agent runs on each node and is responsible for issuing SVIDs to workloads via the workload API" \
      vendor="Red Hat, Inc." \
      release="${RELEASE_VERSION}" \
      io.openshift.tags="spire,identity,spiffe,security" \
      io.openshift.build.commit.id="${COMMIT_SHA}" \
      io.openshift.build.source-location="${SOURCE_URL}" \
      io.openshift.build.commit.url="${SOURCE_URL}/commit/${COMMIT_SHA}" \
      io.k8s.display-name="SPIRE Agent" \
      io.k8s.description="Container image for the SPIRE Agent component, responsible for workload authentication"

ENTRYPOINT ["/spire-agent", "run"]
