FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_golang_1.24 AS builder

ARG SOURCE_DIR="/go/src/github.com/openshift/zero-trust-workload-identity-manager"
WORKDIR $SOURCE_DIR

COPY zero-trust-workload-identity-manager $SOURCE_DIR
COPY zero-trust-workload-identity-manager/LICENSE /licenses/

RUN make build --warn-undefined-variables

FROM registry.redhat.io/ubi9/ubi-minimal:latest@sha256:c7d44146f826037f6873d99da479299b889473492d3c1ab8af86f08af04ec8a0

# Values for below ARGs will passed from tekton configs for konflux builds.
## Release version of the zero-trust-workload-identity-manager source code used in the build.
ARG RELEASE_VERSION
## Commit hash that considered for the image build.
ARG COMMIT_SHA
## github URL of the zero-trust-workload-identity-manager source repository.
ARG SOURCE_URL
ARG SOURCE_DIR="/go/src/github.com/openshift/zero-trust-workload-identity-manager"

COPY --from=builder $SOURCE_DIR/bin/zero-trust-workload-identity-manager /usr/bin/
COPY --from=builder /licenses /licenses

USER 65534:65534

LABEL com.redhat.component="zero-trust-workload-identity-manager-container" \
      name="zero-trust-workload-identity-manager/zero-trust-workload-identity-manager-rhel9" \
      version="${RELEASE_VERSION}" \
      summary="zero-trust-workload-identity-manager" \
      maintainer="Red Hat, Inc." \
      description="zero-trust-workload-identity-manager-container" \
      vendor="Red Hat, Inc." \
      release="${RELEASE_VERSION}" \
      io.openshift.expose-services="" \
      io.openshift.build.commit.id="${COMMIT_SHA}" \
      io.openshift.build.source-location="${SOURCE_URL}" \
      io.openshift.build.commit.url="${SOURCE_URL}/commit/${COMMIT_SHA}" \
      io.openshift.tags="spire,identity,spiffe,security" \
      io.k8s.display-name="openshift-zero-trust-workload-identity-manager" \
      io.k8s.description="zero-trust-workload-identity-manager-container"

ENTRYPOINT ["/usr/bin/zero-trust-workload-identity-manager"]